name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Buid TabShop app realease bundle (ABB)
      id: buildRelease
      run: ./gradlew bundleRelease
    - name: Sign tabShop application bundle
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: android/app/build/outputs/bundle/release
        signingKeyBase64:  ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Upload TabShop app bundle
      id: uploadArtifact
      uses: actions/upload-artifact@v3.2.1
      with:
        name: TabShop
        path: ${{steps.sign.outputs.signedReleaseFile}}
    - name: Write service_account.json (needed for Google Play Publishing) from secreat to a local file
      id: createServiceAccount
      run: echo '{{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
    - name: Upload Android Release to Play Store
      id: deploy
      uses: r0adkll/upload-google-play@v1.1.3
      with:
        # The service account json private key file to authorize the upload request
        serviceAccountJson: service_account.json
        # The package name, or Application Id, of the app you are uploading
        packageName: com.sugarcoachpremium
        # The Android release file(s) to upload (.apk or .aab). Separated by  a ',' for multiple artifacts. Supports glob
        releaseFiles: app/build/outputs/bundle/release/app-release.abb
        # The track in which you want to assign the uploaded app.
        track: beta
        # The directory of localized whats new files
        whatsNewDirectory: whatsnew/
          
